version: "3"
services:
  hub:
    image: dosel/zalenium
    logging:
      driver: "none"
    ports:
      - "4444:4444"
      - "5555:5555"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    command: >
      start --desiredContainers 2
            --maxDockerSeleniumContainers 2
            --maxTestSession 3
            --videoRecordingEnabled false
  flightsearch:
    image: 888777666/selenium-docker
    depends_on:
      - hub
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=testng.xml
    volumes:
      - ./test-output-flight:/usr/share/udemy/test-output          
